### ISSUE TITLE
Accessing Non-RN-core Native packages in a worker thread.

### ISSUE THREAD

**Issue by kinnarshah** [fabriciovergal/react-native-workers#12]
Hello,
Thanks for the fabulous work done on this topic.

Is there any way we can integrate an additional non-RN-core native package into a worker?

We are trying to create a worker that reads the phone-book (a processing-heavy op) and store results for quicker retrieval later.

Outline of my code:

**index.worker.js**:

```
import { WorkerService } from 'rn-workers'
import ContactsBackground from './ContactsBackground';
const worker = new WorkerService();

worker.onmessage = (message) => {
	//Start the worker and pray!
	console.log('Inside worker - outermost');
	ContactsBackground.start();
}
```

**Main worker - ContactsBackground.js**:

```
module.exports = {
	start: function(){
		var Contacts 	= require('react-native-contacts'); //External module of interest
		
		Contacts.getAll((err, contacts) => {

	        // Do something

		});
	}
}
```

The system setup is pretty smooth but the worker halts at Contacts.getAll(...) with a message that Contact.getAll is undefined. (Link to module readme: https://github.com/rt2zz/react-native-contacts )

Any help is very much appreciated.

**Comment by fabriciovergara** [comment]
Hi,

You can build a worker using  RNWorker.Builder to add custom packages for Android.
For iOS all Packages are automatically added.

```java
      final RNWorker worker = new RNWorker.Builder(this, false)
      .entryPoint(RNWorker.DEFAULT_JS_ENTRY_POINT)
      .bundleAsset(RNWorker.DEFAULT_JS_BUNDLE_ASSET)
      .port(8088) //Realm already use 8082 to load a nano server to connect to chrome debug
      .packages(
        new RealmReactPackage()
      ).build();
```

**Comment by kinnarshah** [comment]
Hi Fabricio,
Thanks for the quick reply. Much appreciated.

Can you please expand on this by sharing a bit of code around it?

I have added the snippet in MainApplication.java:
```
 @Override
  public void onCreate() {
    ...
    final RNWorker worker = new RNWorker.Builder(this, false)
                              .entryPoint(RNWorker.DEFAULT_JS_ENTRY_POINT)
                              .bundleAsset(RNWorker.DEFAULT_JS_BUNDLE_ASSET)
                              .packages(
                                new ReactNativeContacts()
                              ).build();
    RNWorkersManager.getInstance().init(this, BuildConfig.DEBUG);
    ...
  }
```
Snippet from MainActivity.java
```
public void onCreate(Bundle savedInstanceState) {
    ...
    RNWorkersManager.getInstance().startWorkers();
    ...
}
```

I am getting an undefined object where I import `react-native-contacts`

Still facing the same problem. Any thoughts on where I could be going wrong here?

**Comment by fabriciovergara** [comment]
```java
@Override
  public void onCreate() {
    ...
    final RNWorker worker = new RNWorker.Builder(this, BuildConfig.DEBUG)
                              .entryPoint(RNWorker.DEFAULT_JS_ENTRY_POINT)
                              .bundleAsset(RNWorker.DEFAULT_JS_BUNDLE_ASSET)
                              .port(RNWorker.DEFAULT_WORKER_PORT)
                              .packages(
                                new ReactNativeContacts()
                              ).build();
    RNWorkersManager.getInstance().init(this, worker);
    ...
  }

```

**Comment by kinnarshah** [comment]
Thanks Fabricio! This worked perfectly! :)

**Comment by guns2410** [comment]
How do we do this in iOS

**Comment by fabriciovergara** [comment]
In iOS all RN Packages are "singletons", so when you create a worker, all custom packages will be automatically linked to this worker.
