### ISSUE TITLE
Error in run-android in RN 0.44

### ISSUE THREAD

**Issue by doniyor2109** [fabriciovergal/react-native-workers#19]
\node_modules\rn-workers\android\src\main\java\com\fabricio\vergal\RNWorkers\RNWorkersUtils.java:8: error: cannot find symbol
import com.facebook.react.modules.debug.DeveloperSettings;
                                       ^
  symbol:   class DeveloperSettings
  location: package com.facebook.react.modules.debug
\node_modules\rn-workers\android\src\main\java\com\fabricio\vergal\RNWorkers\RNWorkersUtils.java:86: error: cannot find symbol
        final DeveloperSettings settings = manager.getDevSupportManager().getDevSettings();
              ^
  symbol:   class DeveloperSettings
  location: class RNWorkersUtils

**Comment by Isarstyle** [comment]
Have the same Issue here, is there anything i can do?

**Comment by doniyor2109** [comment]
I have still no solution for this issue, I just did not use this library yet because of this error. It would be better if there was a solution.

**Comment by fabriciovergara** [comment]
Fixed on 0.1.7 
Thanks @haggholm
