### ISSUE TITLE
Starting: Intent { cmp=com.reactapp/.MainActivity }

### ISSUE THREAD

**Issue by improve-ar** [fabriciovergal/react-native-workers#3]
Hi, i have this error when i try to do react-native run-android

Starting: Intent { cmp=com.reactapp/.MainActivity }

**Comment by fabriciovergara** [comment]
Please, can you provide more details ? Library version, RN version, Android version, code snippet.
have you tried using latest version ? (0.1.2)

Usually this error happens when something went wrong while initializing an Activity, probably there is error logs  before this one.

**Comment by improve-ar** [comment]
Fabricio, sorry for the inconvenience.
The error was caused for other Plugin (Google Maps) when i return it in "getPackage" in "MainAplication" :)
