### ISSUE TITLE
HELPPP

### ISSUE THREAD

**Issue by improve-ar** [fabriciovergal/react-native-workers#4]
i get this error

Attempt to invoke interface method 'java.util.Iterator java.util.List.iteratir()' on a null object reference

**Comment by fabriciovergara** [comment]
Can you provide more information ? Complete stacktrance, Lib version, RN version.
For Android I have made some improvements, can you check if using latest version it still happens ?

**Comment by fabriciovergara** [comment]
Closing for lack of information, please reopen if needed.

**Comment by zoecarver** [comment]
@fabriciovergal I am having the same error - I think it may ave to do with a linking issue. I am going to look into it some more but until then here is some info on it:

### index.worker.js
```js
//index.worker.js
import { WorkerService } from 'rn-workers'

const worker = new WorkerService();

worker.onmessage = message => {
    //Reply the message back to app
    worker.postMessage("Hello from the other side (" + message + ")")
};
```
### index.js
```js
//...
  const worker = new Worker();

  worker.postMessage(JSON.stringify({
    file: file,
    url: item.enclosures[0].url
  }));

  worker.onmessage = (message) => {
    worket.terminate(); 
  }
//...
```
### Versions
react-native-cli: 2.0.1
react-native: 0.49.3
react-native-worker: 0.1.7
android: 7.1.1 and 8.0.0

### Screenshot
![screen shot 2017-10-29 at 7 01 47 pm](https://user-images.githubusercontent.com/13806068/32151658-de4023e6-bcdb-11e7-8937-abdfc57c5912.png)

### Discription
This error occurs when a the worker is started `const worker = new Worker()`.

I will update this when I have more info :)
