### ISSUE TITLE
can workers use native modules?

### ISSUE THREAD

**Issue by mvayngrib** [fabriciovergal/react-native-workers#5]
first off, thanks for continuing to improve this library :)

question: i want to [sign/verify](https://github.com/tradle/react-native-ecc) some data, or throw some big item in AsyncStorage, and take advantage of the separate bridge the worker uses to avoid clogging the main bridge. Is this something I can do with this module? If yes, could you give a primitive example? Thanks!

**Comment by fabriciovergara** [comment]
Yes, is possible to use native modules.
On iOS you don't need to write any additional code, but on Android you have to use RNWorker.Builder. 



```java
      final RNWorker worker = new RNWorker.Builder(this, BuildConfig.DEBUG)
           .entryPoint(RNWorker.DEFAULT_JS_ENTRY_POINT)
          .bundleAsset(RNWorker.DEFAULT_JS_BUNDLE_ASSET)
          .port(RNWorker. DEFAULT_WORKER_PORT)
          .packages(new NativeModule1(), new NativeModule2()) // 
          .build();

    RNWorkersManager.getInstance().init(this, worker);
```

All RN Core libraries and RNWorker is automatically included.
Thanks for opening this issue, I'll update the docs with it.

**Comment by mvayngrib** [comment]
@fabriciovergal thanks for getting back to me so quickly. Do I understand correctly that calls to native modules made from the worker js file will go over the worker bridge?

**Comment by fabriciovergara** [comment]
@mvayngrib Yes, it will go  over worker bridge, but the worker bridge is finished at the same time of main bridge. 
So, this library is currently supporting no background task support, such Androids services.

I have created this library to execute very CPU intensive algorithms outside of RN "UI thread" and get back the result to RN js main code. 

I'm planning to add this kind of support, but I still could not find a good/safe way to do so.

**Comment by fabriciovergara** [comment]
For Android Its pretty easy to close the worker only when requested (without worrying about Doze), but for iOS  I could not find a good solution probably because I don't have too much experience with background work on this platform.

**Comment by mvayngrib** [comment]
@fabriciovergal yea, i don't really have experience with background mode on either platform. I'm looking forward to playing with this soon!
